version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-updated"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i0cl5hbvjzk8"
s3_prefix = "sam-updated"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["LibrariesFunction=[AWS_ACCOUNT_ID].dkr.ecr.ap-southeast-2.amazonaws.com/sam-updated-lambda"]
