AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-updated

  Sample SAM Template for sam-updated

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LibrariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Libraries:
          Type: Api
          Properties:
            Path: /libraries
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./libraries
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LibrariesApi:
    Description: 'API Gateway endpoint URL for Prod stage for Libraries function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
  LibrariesFunction:
    Description: 'Libraries Lambda Function ARN'
    Value: !GetAtt LibrariesFunction.Arn
  LibrariesFunctionIamRole:
    Description: 'Implicit IAM Role created for Libraries function'
    Value: !GetAtt LibrariesFunctionRole.Arn
